### ISSUE TITLE
How to use this to load FBX files

### ISSUE THREAD

**Issue by nikhilcheruku12** [googlevr/media-app-template#2]
Does anyone have a clue about how to use the media app template to load fbx files the same way that photos and videos are loaded?

**Comment by dsternfeld7** [comment]
The Media App Template isn't built for viewing models. However, here are some starting points you can use to begin adapting it for that use:

- In MediaHelpers.cs add a MediaType called model and add the appropriate extensions to the EXTENSIONS_TO_MEDIA_TYPE dictionary.
- Create a subclass of BaseMediaPlayer to display models.
- In MediaSelector.CreateMediaPlayer, add support for the Model media type.
